---
repo-name: peripherals-kinetic-core
categories:
- Service Management
- Request Management
- CRM
- DevOps
- Ticketing
display-name: Kinetic Core
manufacturer: Kinetic Data
product: Reqeust CE
description: The Core component of the Kinetic Platform, (commonly referred to as Kinetic Request CE).
