---
repo-name: peripherals-kinetic-core
categories:
- Service Management
- Request Management
- CRM
- DevOps
- Ticketing
display-name: Kinetic Request CE
manufacture: Kinetic
product: Reqeust CE
